apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wbtour2bc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wbtour2bc-go 
  name: wbtour2bc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wbtour2bc-go 
